title: Pradyun Hebbar
description: Physics PhD Portfolio
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://pradyunhebbar.github.io" # the base hostname & protocol for your site

# Theme settings
remote_theme: just-the-docs/just-the-docs
#color_scheme: dark

# Aux links for the upper right navigation
aux_links:
  "GitHub": "https://github.com/PradyunHebbar"
  "LinkedIn": "https://www.linkedin.com/in/pradyun-hebbar"

# Makes Aux links open in a new tab
aux_links_new_tab: true

# Enable or disable heading anchors
heading_anchors: true

# Back to top link
back_to_top: true
back_to_top_text: "Back to top"

# Footer content
footer_content: "Copyright &copy; 2024 Pradyun Hebbar."

# Search
search_enabled: true
search:
  heading_level: 2
  previews: 3
  preview_words_before: 5
  preview_words_after: 10
  tokenizer_separator: /[\s/]+/
  rel_url: true
  button: false
