title: Pradyun Hebbar
description: Physics PhD Portfolio
baseurl: "/" 
url: "https://PradyunHebbar.github.io"

# Theme settings
remote_theme: just-the-docs/just-the-docs

# Navigation structure
nav_external_links:
  - title: GitHub
    url: https://github.com/PradyunHebbar
    opens_in_new_tab: true

# Collections
collections:
  _projects:
    output: true
    permalink: /projects/:name/
  _experiences:
    output: true
    permalink: /experiences/:name/

# Defaults for collections and pages
defaults:
  - scope:
      path: ""
      type: "_projects"
    values:
      layout: project
      parent: Projects
  - scope:
      path: ""
      type: "_experiences"
    values:
      layout: experience
      parent: Experiences

# Enable or disable heading anchors
heading_anchors: true

# Back to top link
back_to_top: true
back_to_top_text: "Back to top"

# Footer content
footer_content: "Copyright &copy; 2024 Pradyun Hebbar. Website powered by Jekyll with Just the Docs theme."

# Search
search_enabled: true
search:
  heading_level: 2
  previews: 3
  preview_words_before: 5
  preview_words_after: 10
